### PR TITLE
Issue 17 - add flag to disable danger check

### PR DESCRIPTION
**Pull request by jfelten**
Added flag to seleium agent class to disable security checking.

Update dependency libs

### CODE REVIEW

**Comment by handrew** [comment]
Taking a look now. The code changes seem fine to me. Instead of the poetry lock, could you revert that change and just change the pyproject.toml instead?

**Comment by handrew** [comment]
@jfelten is there anything else I can help with? Let me know and I'll be ready to merge soon

**Comment by jfelten** [comment]
@handrew sorry for the delay - Did testing on my own scripts and it seems to work. There are some problems though with the examples. Only about half of them work with gpt-4. I'm not sure if you want to address that here or not

Also I used gpt-4 for the instruction compiler vs gpt-4o-mini. The cost is significantly higher, but it is less error-prone.

Overall I find this very useful and hope to contribute more.

**Comment by handrew** [comment]
Hi, apologies for the delay on my end. Been pretty busy. I think everything looks good to me except the `poetry.lock`—can you revert that change and just make changes to the `pyproject.toml` instead? Once you do that I can merge.

**Comment by jfelten** [comment]
ok let me check - I forget which lib needed updating

**Comment by jfelten** [comment]
I reverted the poetry.lock file and bumped the patch version in pyproject.toml. The poetry.lock file was regenerated because poetry install failed.

**Comment by handrew** [comment]
Wait but which of the dependencies needed updating?

**Comment by jfelten** [comment]
ok I ran poetry update then updated the dependencies in pyproject.yaml to the versions specified.

**Comment by jfelten** [comment]
may want to consider adding a .gitignore for the lock file

**Comment by handrew** [comment]
thank you! try to merge by this weekend, and yes, good call, will ignore the lock file from now on...

**Review by handrew — APPROVED** [review]

**Comment by handrew** [comment]
Merging, but will make a few changes before I actually push to pypi.

**Comment by handrew** [comment]
@jfelten I removed the danger checking from InstructionCompiler entirely. It's only in GPTSeleniumAgent now. 

It is now available in pypi, version 0.2.53. Hope it works for you, and doesn't break anything for anyone else...

**Pull request merged**
