### PR TITLE
Fix | Update langchain openai import and remove LLMPredictor and Service context while invoking vector store index

### PR DESCRIPTION
**Pull request by AryanMadhavVerma**
1) `from langchain_community.chat_models import ChatOpenAI` is now not supported and the newer import is `from langchain_openai import ChatOpenAI`

2) Using `LLMPredictor` and `service_context` is giving a callback error whenever the llm is called. 
The error that comes is this 
`ValueError: Cannot use llm_chat_callback on an instance without a callback_manager attribute.`
Removing the service_context and purely using `GPTVectorStoreIndex.from_documents([Document(text=text)])` resolves this and browserpilot works perfectly well after that. 

Note:
LLMPredictor has been deprecated. Need to update the RAG part of the code

### CODE REVIEW

**Comment by handrew** [comment]
Thanks @AryanMadhavVerma! I will take a look later today and merge asap.

**Comment by handrew** [comment]
@AryanMadhavVerma Do we still need `LLMPredictor` or `ServiceContext` at all? Could we also remove those imports? Similarly, do we need `langchain-community` as a requirement in the `pyproject.toml`? If not, could you also remove that? 

Thanks again for the contribution. After that I think it should be good.

**Comment by AryanMadhavVerma** [comment]
No we don't. I've removed the unused dependency and the `LLMPredictor` code I commented out.

Also, amazing job on this repository. I'm already thinking of a lot of downstream use-cases using this functionality. Will keep contributing as and when I iterate on this.

**Comment by handrew** [comment]
Thanks for the kind words.

Actually, there are a few more mentions of LLMPredictor that need to be factored out. I won't be able to take a look at it for a bit. It's in the `__init__.py` file defining the Memory class, if you could take a stab.

**Comment by AryanMadhavVerma** [comment]
Thanks for merging. Actually I didn't tinker around much with the memory module. Was using the default state for experimentation. But I see you made the changes. Thanks!

**Comment by handrew** [comment]
Yep! Thanks for the contribution!

**Pull request merged**
